[versions]
moulconfig = "4.7.2"
nealisp = "1.1.0"
minecraft = "26.1.2"
fabric-loader = "0.19.2"
fabric-api = "0.150.0+26.1.2"
kotlin = "2.2.21"
ksp = "2.3.9"
loom = "1.15-SNAPSHOT"
detekt = "1.23.8"
detektrules-neu = "1.0.0"

[libraries]
nealisp = { module = "moe.nea:nealisp", version.ref = "nealisp" }
moulconfig = { module = "org.notenoughupdates.moulconfig:modern-26.1", version.ref = "moulconfig" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
detekt-api = { module = "io.gitlab.arturbosch.detekt:detekt-api", version.ref = "detekt" }
detektrules-ktlint = { module = "io.gitlab.arturbosch.detekt:detekt-rules-ktlint", version.ref = "detekt" }
detekt-test = { module = "io.gitlab.arturbosch.detekt:detekt-test", version.ref = "detekt" }
detektrules-neu = { module = "org.notenoughupdates:detektrules", version.ref = "detektrules-neu" }
detektrules-authors = { module = "io.gitlab.arturbosch.detekt:detekt-rules-ruleauthors", version.ref = "detekt" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
