name: Check banned imports

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-imports:
    name: Scan for illegal imports
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check imports
        run: .github/workflows/ban-imports.sh
