name: PR Naming Convention

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  verify-pr-name:
    name: Check PR title format
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '(?:meta:|Add|Fix|Remove|Port|Improve|Refactor|Update) .+[^\.]'
          prefix_case_sensitive: true
          github_token: ${{ github.token }}
